### ISSUE TITLE
Does it support Mac?

### ISSUE THREAD

**Issue by JinEui-Kim** [finaldie/auto-news#1]
Hi, what a great project!

I have Windows desktop and Macbook, but I want to try your project.
Does this project support mac?

**Comment by finaldie** [comment]
Thank you for bringing this question up, it (the backend) could support Mac and maybe need a little adjustment, I'll test it out after I clear out the current work (notion entry page automation), which could be in a few days, stay tuned :)

**Comment by finaldie** [comment]
> Hi, what a great project!
> 
> I have Windows desktop and Macbook, but I want to try your project. Does this project support mac?

Thank you for bringing this question up, it (the backend) could support Mac and maybe need a little adjustment, I'll test it out after I clear out the current work (notion entry page automation), which could be in a few days, stay tuned :)

**Comment by JinEui-Kim** [comment]
Thank you for considering my question!
