### ISSUE TITLE
Summary is put into 'Translation' Notion Block when no translation is chosen

### ISSUE THREAD

**Issue by sebnapi** [finaldie/auto-news#101]
<img width="1005" alt="Screenshot 2024-09-29 at 16 53 55" src="https://github.com/user-attachments/assets/8319924e-91f2-475e-8441-5cab0064fff2">

**Comment by finaldie** [comment]
hi @sebnapi 

Thanks for raising the issue, may I know model you are using?

**Comment by sebnapi** [comment]
Hi! I use gemini-1.5-flash-latest (because of it's free tier atm).

**Comment by sebnapi** [comment]
Cheers, will have a look and report back!

**Comment by finaldie** [comment]
Feel free to re-open if the above doesn't work for u.
