### ISSUE TITLE
everytime i do "make start" it creates new notion page configs and dags only process new ones

### ISSUE THREAD

**Issue by kentdtran** [finaldie/auto-news#108]
![image](https://github.com/user-attachments/assets/66e2b483-9902-4813-a080-db7d1d22640d)

the repeated entry pages get created. how can i start the service without doing the initialization?

also, when the pull job runs, it only loads the rss created in the new pages not the existing pages.

**Comment by finaldie** [comment]
This is weird. The initialization will only apply once. The above case will only happen if the local `workspace` folder is removed from the previous shutdown. Could you double-check whether you deleted it every shutdown? what's your actual operation steps?

**Comment by kentdtran** [comment]
I use the commands make stop and make start

**Comment by kentdtran** [comment]
make stop removes all the images. and make start creates all images from scratch again.
i just want to update code and rebuild the airflow code

**Comment by kentdtran** [comment]
![image](https://github.com/user-attachments/assets/b71a62b2-5250-47dd-8880-bd2df822c19f)
This is the only git diff re make file and/or docker compose

I always have this issue, make stop removes all containers completely.

**Comment by finaldie** [comment]
@kentdtran thank you for providing the details, it make sense now why you always have this issue.

The above docker volume mapping changes will cause Mysql and Postgres not to recognize the data folder, as Mysql only uses `/var/lib/mysql` by default, and Postgres uses `/var/lib/postgresql` by default. Changing this mapping makes them think the data folder is empty, aka an empty database, so every time you restart, it will refresh the database and never get persistent into the `workspace` folder.

Revert the above changes will solve the issue. A side question: what's the motivation for the changes?

**Comment by kentdtran** [comment]
I have multiple postgres environments so I changed the data folder since I didnt want to overwrite my current dockers (im not the best at docker!!)

**Comment by kentdtran** [comment]
Thank you for the support!! I hope to push some PRs to improve the functionality in future

**Comment by finaldie** [comment]
> I have multiple postgres environments so I changed the data folder since I didnt want to overwrite my current dockers (im not the best at docker!!)

It won't, as the Postgres/MySQL docker is only for the auto-news project, and data has persisted into the local `workspace` folder; there is no relationship with other docker containers in your machine.

> Thank you for the support!! I hope to push some PRs to improve the functionality in future

You are welcome and looking forward to it, cheers.
