### ISSUE TITLE
API integration

### ISSUE THREAD

**Issue by theobouwman** [finaldie/auto-news#39]
What would be a good starting point to integrate this using an API and for example display the result in React Native etc?

**Comment by finaldie** [comment]
Hi @theobouwman,

Thank you for the question. At this moment, I would recommend pulling data from Notion database (e.g. `ToRead` database) via [Notion API](https://developers.notion.com/)

Below is the high-level data flow of AutoNews:
![image](https://github.com/finaldie/auto-news/assets/1088543/f3511224-9b63-402c-880d-8574d3a5c9dc)
