### ISSUE TITLE
How do you create the infra animations?

### ISSUE THREAD

**Issue by maxabrahamsson** [finaldie/auto-news#54]
Hi!

I love the project. I was looking to build something similar for myself and was very happy to found your work here. 

I just noticed you made some really cool animations depicting the infrastructure workings of the project. I mean the animation in the video, but also saw similar animation in your profile.

How do you create such animations? Is there a tool to quickly generate these?

Thank you for your great work and sharing it open-source.
Cheers!

**Comment by finaldie** [comment]
Hi @maxabrahamsson,

Thank you for loving this project. I hope it will be useful for you. For the animation in my previous videos was created using my another ad-hoc project that is based on svgjs and threejs. To be honest, it's not easy to use. However, from my research, I have found that other YouTubers suggest using 'draw.io', it may be easier to use, but I haven't personally tried it yet.
