### ISSUE TITLE
Functional suggestion. 

### ISSUE THREAD

**Issue by zuenko** [finaldie/auto-news#59]
I want to develop a feature that would automatically research a specified topic, add it to articles, YouTube and other ToRead, and Lists, and then run dags as usual. According to your UML, sources should be provided by some search algorithm or API in addition you to a user. 

Additionally, I might want to explore a particular topic; I would write this topic Title to notion page "Inbox - Research", and it would prepare a summary based on information collected across search engine.

Another suggestion is language detection. I've noticed it sometimes translates from the target language back to the target language. This issue should be addressed.

An improvement to include would be the detection of language translation, specifically preventing translations from and to the same language, to optimize costs.

I'm ready to assist with the "auto-news" project, though I haven't fully immersed myself in it yet. I'm eager to learn quickly, as the tool has already proven immensely useful to me. I aim to eliminate the tedious process of opening 20-30 sources on Google, transferring them to notion, and then waiting for summaries. I'd appreciate guidance on where to start to contribute effectively.

**Comment by finaldie** [comment]
```
Another suggestion is language detection. I've noticed it sometimes translates from the target language back to the target language. This issue should be addressed.
```

Yeah, we need to handle this case accordingly.

**Comment by finaldie** [comment]
Assume that there is no urgency for this, will add it to the backlog. Feel free to reopen.
