### ISSUE TITLE
How to use local LLM API ?

### ISSUE THREAD

**Issue by papiche** [finaldie/auto-news#78]
I wonder how to use [ollama](https://github.com/ollama/) local model instead of "Cloud GPT"?

**Comment by finaldie** [comment]
@papiche, Thank you for raising it, that needs an `ollama` backend provider, and user could easily switch to it, I'll do some tests recently. In the meantime, in case if you already have a PR in hand, feel free to submit it. :+1:

**Comment by finaldie** [comment]
hi @papiche , I updated the wiki [Install via docker compose](https://github.com/finaldie/auto-news/wiki/Docker-Installation). Feel free to check the latest main branch and have a try; let me know if you have any questions; thanks.
