### ISSUE TITLE
docker install [portainer]

### ISSUE THREAD

**Issue by nsk** [finaldie/auto-news#79]
hi would it be possible for you to provide us with an example for an installation from portainer?? and moreover impossible to recover an API key from reddit since the changes occurred in 2023?

thank you your project looks nice

**Comment by finaldie** [comment]
hi @nsk, thank you for loving the project. 

> would it be possible for you to provide us with an example for an installation from portainer?

I haven't tried Portainer yet, as it is a view layer on top of Docker. I guess it would be smooth. I'll do some setup and write a wiki page for it then.

> and moreover impossible to recover an API key from reddit since the changes occurred in 2023?

I am not sure what exactly changes and why it cannot be recovered. Would you mind providing more details? thanks.

**Comment by finaldie** [comment]
hi @nsk , I've wrote a wiki for the Portainer, feel free to check it out, and let me know if any questions. https://github.com/finaldie/auto-news/wiki/Installation-using-Portainer
